on:
  workflow_dispatch:
  push:
    branches: [main]

# Only allow one copy of this job to run at a time.
# This ensures no merge or cache conflicts.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  fuzz:
    runs-on: [ubuntu-24.04]
    steps:
      - name: install llvm
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo ln -s $(which llvm-config-18) /usr/bin/llvm-config
          llvm-config --version

      - name: install zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: checkout roc-compiler-fuzz
        uses: actions/checkout@v4
        with:
          path: roc-compiler-fuzz

      - name: checkout roc
        uses: actions/checkout@v4
        with:
          path: roc
          repository: roc-lang/roc

      - name: build roc fuzzer (base)
        run: |
          cd roc
          # TODO: figure out why fuzzers won't build.
          zig build -Dfuzz -Dtarget=native-native

          mv zig-out/bin/fuzz-tokenize ../fuzz-tokenize.afl

      # cmplog enables extracting comparision info to get better fuzz results.
      - name: build roc fuzzer (cmplog)
        env:
          AFL_LLVM_CMPLOG: 1
        run: |
          cd roc
          rm -rf .zig-cache zig-out

          zig build -Dfuzz -Dtarget=native-native

          mv zig-out/bin/fuzz-tokenize ../fuzz-tokenize.cmplog

      # load cached corpus
      - name: load cached corpus
        id: restore-cache-corpus
        uses: actions/cache/restore@v4
        with:
          key: fuzz-tokenize-corpus
          path: fuzz-tokenize-corpus
      
      # No matter what we reload examples from the repo.
      # They might get pruned, but we want to make sure we don't miss any new examples.
      - name: copy over initial corpus
        run: |
          mkdir -p fuzz-tokenize-corpus/
          cp roc/src/fuzz-corpus/tokenize/* fuzz-tokenize-corpus/

      - name: configure system for fuzzing
        run: |
          sudo ./roc/zig-out/AFLplusplus/bin/afl-system-config
      
      # launch fuzzer on corpus for x amount of time
      - name: fuzz tokenizer
        env:
          AFL_TESTCACHE_SIZE: 500
          AFL_IGNORE_SEED_PROBLEMS: 1
          AFL_IMPORT_FIRST: 1
          AFL_FINAL_SYNC: 1
        run: |
          # This is a rough attempt to follow best practices from: https://aflplus.plus/docs/fuzzing_in_depth/#c-using-multiple-cores
          # TODO: decide runtime (currently 10 minutes)
          ./roc/zig-out/AFLplusplus/bin/afl-fuzz \
              -i fuzz-tokenize-corpus/ \
              -o fuzz-out/ \
              -V 600 \
              -M main \
              -c ./fuzz-tokenize.cmplog \
              -l 2AT \
              -p explore \
              -- ./fuzz-tokenize.afl &
          ./roc/zig-out/AFLplusplus/bin/afl-fuzz \
              -i fuzz-tokenize-corpus/ \
              -o fuzz-out/ \
              -V 600 \
              -S s1 \
              -p fast \
              -c ./fuzz-tokenize.cmplog \
              -- ./fuzz-tokenize.afl &
          AFL_DISABLE_TRIM=1 ./roc/zig-out/AFLplusplus/bin/afl-fuzz \
              -i fuzz-tokenize-corpus/ \
              -o fuzz-out/ \
              -V 600 \
              -S s2 \
              -p explore \
              -- ./fuzz-tokenize.afl &
          ./roc/zig-out/AFLplusplus/bin/afl-fuzz \
              -i fuzz-tokenize-corpus/ \
              -o fuzz-out/ \
              -V 600 \
              -S s3 \
              -p exploit \
              -- ./fuzz-tokenize.afl &
          wait
      
      - name: fuzz stats
        run: |
          ./roc/zig-out/AFLplusplus/bin/afl-whatsup -d -s fuzz-tokenize-corpus/

      # minimize the corpus and all examples
      - name: minimize corpus
        run: |
          ./roc/zig-out/AFLplusplus/bin/afl-cmin \
              -i fuzz-out/main/queue/ \
              -o fuzz-cmin/ \
              -- ./roc/zig-out/bin/fuzz-tokenize

          mkdir fuzz-tmin
          cd fuzz-cmin
          parallel \
            ../roc/zig-out/AFLplusplus/bin/afl-tmin \
                -i {} \
                -o ../fuzz-tmin/{} \
                -- ../roc/zig-out/bin/fuzz-tokenize \
            ::: *
          cd ..

          rm -rf fuzz-tokenize-corpus
          mv fuzz-tmin fuzz-tokenize-corpus

      # save the corpus to cache
      - name: save corpus
        id: save-cache-corpus
        uses: actions/cache/save@v4
        with:
          key: fuzz-tokenize-corpus
          path: fuzz-tokenize-corpus

      # minimize all crashes
      - name: minimize crashes
        run: |
          mv fuzz-out/main/crashes/ fuzz-crashes
          mv fuzz-out/main/hangs/ fuzz-hangs

          mkdir fuzz-crashes-tmin
          cd fuzz-crashes
          parallel \
            ../roc/zig-out/AFLplusplus/bin/afl-tmin \
                -i {} \
                -o ../fuzz-crashes-tmin/{} \
                -- ../roc/zig-out/bin/fuzz-tokenize \
            ::: *

      # calculate list of crashes/hangs to report
      
      # update this repo with new failures and stats on passes
      # store inputs in base64 to make easy to copy commands
