on:
  workflow_dispatch:
  push:
    branches: [main]

# Only allow one copy of this job to run at a time.
# This ensures no merge or cache conflicts.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  fuzz:
    runs-on: [ubuntu-22.04]
    steps:
      - name: install llvm
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo ln -s $(which llvm-config-18) /usr/bin/llvm-config
          llvm-config --version

      - name: install zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: checkout roc-compiler-fuzz
        uses: actions/checkout@v4
        with:
          path: roc-compiler-fuzz

      - name: checkout roc
        uses: actions/checkout@v4
        with:
          path: roc
          repository: roc-lang/roc

      - name: build roc fuzzers
        run: |
          cd roc
          # TODO: figure out why fuzzers won't build.
          # zig build -Dfuzz -Dtarget=native-native

      # load cached corpus
      - name: load cached corpus
        id: restore-cache-corpus
        uses: actions/cache/restore@v4
        with:
          key: fuzz-tokenize-corpus
          path: fuzz-tokenize-corpus
      
      # No matter what we reload examples from the repo.
      # They might get pruned, but we want to make sure we don't miss any new examples.
      - name: copy over initial corpus
        run: |
          echo $(pwd)
          mkdir -p fuzz-tokenize-corpus/
          cp roc/src/fuzz-corpus/tokenize/* fuzz-tokenize-corpus/

      # launch fuzzer on corpus for x amount of time
      
      # minimize the corpus

      # minimize all examples in the corpus

      # save the corpus to cache
      - name: save corpus
        id: save-cache-corpus
        uses: actions/cache/save@v4
        with:
          key: fuzz-tokenize-corpus
          path: fuzz-tokenize-corpus

      # minimize all crashes

      # calculate list of crashes/hangs to report
      
      # update this repo with new failures and stats on passes
